config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "designs#index"
  resources :designs do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  has_attached_file  :image , styles: {medium: "300x300", thumb: "100x100"}
  validates_attachment_content_type  :image , content_type: ["image/jpg","image/jpeg","image/png"]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :design, counter_cache: :likes_count
  belongs_to :user

  validates :user_id, uniqueness: {scope: :design_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :designs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController

  before_action :authenticate_user!

  def index
    @designs = Design.all
    @like = Like.find_by(user_id: current_user.id)
    @likes = Like.where(design_id: params[:design_id])
    # binding.pry
  end

  def new
    @design = Design.new
  end

  def create
    design = Design.create(design_params)
  end

  def show
    @design = Design.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    design = Design.find(params[:id])
    design.destroy
    redirect_to :root, notice: 'デザインを削除しました。'
  end

  private
    def design_params
      params.require(:design).permit(:image, :comment).merge(user_id: current_user.id)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, design_id: params[:design_id])
    @likes = Like.where(design_id: params[:design_id])
    @design =Design.find(params[:design_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, design_id: params[:design_id])
    @likes = Like.where(design_id: params[:design_id])
    like.destroy
    @design =Design.find(params[:design_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/designs/create.html.haml
%p デザインが投稿されました。
= link_to 'デザイン一覧へ戻る', designs_path

app/views/designs/index.html.haml
%h1 デザイン一覧
- @designs.each do |design|
  .image{style: "background-image: url(#{design.image.url(:medium)}); width: 300px; height: 200px;"}
  = design.comment
  %span{id: "like-of-#{design.id}"}
    = render partial: 'likes/like', locals: { design: design, like: @like }
  - if design.user_id == current_user.id
    = link_to 'このデザインを削除する', design_path(design.id)

app/views/designs/new.html.haml
%h1 デザインを登録する
= form_for @design do |f|
  %h2 画像
  %p 投稿する画像は◯バイト以下としてください。
  = f.file_field :image, require:true, label: '画像URL'
  %h2 コメント
  = f.text_field :comment, require:true
  = f.submit 'デザインを登録する'

app/views/designs/show.html.haml
%h1 このデザインを削除してよろしいですか？
.image{style: "background-image: url(#{@design.image.url(:medium)}); width: 300px; height: 200px;"}
= @design.comment
=link_to '削除する', design_path(@design.id), method: :delete

app/views/layouts/_header.html.haml
=link_to 'ログアウト', destroy_user_session_path, method: :delete
/ =link_to 'ログイン'. new_user_session_path
=link_to 'サインアップ', new_user_registration_path
=link_to 'デザインを登録する', new_design_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AthenaWaterBottleDesign
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"}
  %body
    - flash.each do |key, value|
      = content_tag(:div, value, class: "#{key}")
    = render partial: 'layouts/header'
    = yield

app/views/likes/_like.html.haml
- if user_signed_in?
  - if design.like_user(current_user.id)
    = button_to design_like_path(like, design_id: design.id), method: :delete, id: 'like-button', remote: true do
      = image_tag('like_black.png')
      .span
      = design.likes_count
      .span
  - else
    = button_to design_likes_path(design), id: 'like-button', remote: true do
      = image_tag('like_white.png')
      .span
      = design.likes_count
      .span
- else
  = image_tag('like_white.png')
  .span
  = design.likes_count
  .span

app/views/likes/create.js.haml
$("#like-of-#{@design.id}").html("#{j(render partial: 'likes/like', locals: { design: @design, like: @like })}")

app/views/likes/destroy.js.haml
$("#like-of-#{@design.id}").html("#{j(render partial: 'likes/like', locals: { design: @design})}");